[GLOBAL]
# Colors often work in CI, but the shell is usually not a TTY so Pants
# doesn't attempt to use them by default.
colors = true

[stats]
log = true

[test]
use_coverage = true
extra_env_vars = ["PYTHONDEVMODE=1", "PYTEST_DISABLE_PLUGIN_AUTOLOAD=1", "PYTEST_PLUGINS=pytest_asyncio.plugin", "LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/ros/jazzy/opt/rviz_ogre_vendor/lib:/opt/ros/jazzy/lib/x86_64-linux-gnu:/opt/ros/jazzy/opt/gz_math_vendor/lib:/opt/ros/jazzy/opt/gz_utils_vendor/lib:/opt/ros/jazzy/opt/gz_cmake_vendor/lib:/opt/ros/jazzy/lib:/opt/ros/jazzy/opt/sdformat_vendor/lib", "HOME=/tmp"]

[coverage-py]
interpreter_constraints = ["==3.12.*"]
report = ["xml"]
global_report = true

[pytest]
args = ["-p", "pytest_asyncio", "-p", "pytest_cov", "-vv", "--no-header"]
