version: '3'

services:
  arcor:
    image: arcor2_arserver:latest
    container_name: arcor2
    depends_on:
      - pickmaster-storage
    ports:
      - "6789:6789"
    environment:
      - ARCOR2_PERSISTENT_STORAGE_URL=http://pickmaster-storage:11000    
      - ARCOR2_EXECUTION_URL=ws://arcor2_execution:6790
  arcor2_build:
    image: arcor2_build:latest
    container_name: arcor2_build
  arcor2_execution:
    image: arcor2_execution:latest
    container_name: arcor2_execution
    environment:
      - ARCOR2_BUILDER_URL=http://arcor2_build:5007
  pickmaster-storage:
    image: kinalisoft/storage:0.3.1
    container_name: "pickmaster-storage"
    ports:
      - "11000-11001:11000-11001"
    environment:
      MONGODB_URL: pickmaster-mongodb:27017
    links:
        - pickmaster-mongodb
    depends_on:
        - pickmaster-mongodb

  pickmaster-mongodb:
    image: mongo:4.2.0-bionic
    container_name: "pickmaster-mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - mongodb:/data/db
    expose:
      - "27017"

volumes:
  mongodb:   

