version: '3'

services:
  arserver:
    image: arcor2/arcor2_arserver:${ARCOR2_VERSION:?ARCOR2_VERSION env variable not set}
    container_name: arserver
    depends_on:
      - project
      - build
      - execution
      - testitoff-robot-webapi
      # - mocks
    ports:
      - "6789:6789"
    networks:
          - testitoff-robot-network
          - testitoff-search-network
          - testitoff-barcode-network
          - testitoff-statistic-network 
          - testitoff-interaction-network
    environment:
      # - ARCOR2_PERSISTENT_STORAGE_URL=http://mocks:5012
      - ARCOR2_PERSISTENT_STORAGE_URL=http://project:10000
      # - ARCOR2_SCENE_SERVICE_URL=http://mocks:5013
      - ARCOR2_SCENE_SERVICE_URL=http://testitoff-scene-webapi:15000
      - ARCOR2_EXECUTION_URL=ws://execution:6790
      - ARCOR2_BUILD_URL=http://build:5008
      - ARCOR2_DATA_PATH=/root/data

  mocks:
    image: arcor2/arcor2_mocks:${ARCOR2_VERSION:?ARCOR2_VERSION env variable not set}
    container_name: mocks
    networks:
          - testitoff-robot-network


  build:
    image: arcor2/arcor2_build:${ARCOR2_BUILD_VERSION:?ARCOR2_BUILD_VERSION env variable not set}
    container_name: build
    environment:
      # - ARCOR2_PERSISTENT_STORAGE_URL=http://mocks:5012
      - ARCOR2_PERSISTENT_STORAGE_URL=http://project:10000
      - ARCOR2_PROJECT_PATH=/root/project
    ports:
      - "5008:5008"
    networks:           
      - testitoff-robot-network
  execution:
    image: arcor2/arcor2_execution:${ARCOR2_EXECUTION_VERSION:?ARCOR2_EXECUTION_VERSION env variable not set}
    container_name: execution
    networks:
          - testitoff-robot-network
          - testitoff-search-network
          - testitoff-barcode-network 
          - testitoff-statistic-network           
          - testitoff-interaction-network
    environment:
      - ARCOR2_SCENE_SERVICE_URL=http://testitoff-scene-webapi:15000
      - ARCOR2_PROJECT_PATH=/root/project
    volumes:
        - execution:/root/project

  execution-proxy:
    image: arcor2/arcor2_execution_proxy:${ARCOR2_EXECUTION_VERSION:?ARCOR2_EXECUTION_VERSION env variable not set}
    container_name: execution-proxy
    environment:
      - ARCOR2_EXECUTION_PROXY_DB_PATH=/root/tokens
      - ARCOR2_EXECUTION_URL=ws://execution:6790
      - ARCOR2_PROJECT_PATH=/root/project
    volumes:
      - execution-proxy:/root/tokens
      - execution:/root/project
    ports:
      - "5009:5009"
    networks:
      - testitoff-robot-network
    depends_on:
      - execution

  testitoff-robot-webapi:
      image: registry.gitlab.com/kinalisoft/test-it-off/robot:0.7.0
      container_name: "testitoff-robot-webapi"
      expose:
          - "13000"
      environment:
          - MONGODB_URL=testitoff-robot-mongodb:27017
          - ROBOTSYSTEM_SERVICE_URL=http://testitoff-robotsystem-webapi:14000
      ports:
        - "13000:13000"
      links:
          - project
      restart: always
      networks:
        - testitoff-robot-network
  testitoff-robot-mongodb:
      image: mongo:4.2.0-bionic
      container_name: "testitoff-robot-mongodb"
      restart: always
      environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
      volumes:
          - testitoff-robot-mongodb:/data/db
      networks:
          - testitoff-robot-network
      expose:
          - "27017"
      ports:
          - "13017:27017"  

  testitoff-robotsystem-webapi:
      image: registry.gitlab.com/kinalisoft/test-it-off/robotsystem/simulator:0.2.0
      container_name: "testitoff-robotsystem-webapi"
      expose:
          - "14000"
      environment:
          - MONGODB_URL=testitoff-robotsystem-mongodb:27017
      ports:
        - "14000:14000"
      restart: always
      networks:
        - testitoff-robot-network
  testitoff-robotsystem-mongodb:
      image: mongo:4.2.0-bionic
      container_name: "testitoff-robotsystem-mongodb"
      restart: always
      environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
      volumes:
          - testitoff-robotsystem-mongodb:/data/db
      networks:
          - testitoff-robot-network
      expose:
          - "27017"
      ports:
          - "14017:27017"  

  
  testitoff-search-webapi:
        image: registry.gitlab.com/kinalisoft/test-it-off/search-simulator:0.5.0-beta.7
        container_name: "testitoff-search-webapi"
        privileged: true
        restart: always
        environment:
          - MONGODB_URL=testitoff-search-mongodb:27017
        ports:
          - "12000:12000"
        networks:
          - testitoff-search-network

  testitoff-search-mongodb:
        image: mongo:4.2.0-bionic
        container_name: "testitoff-search-mongodb"
        restart: always
        environment:
            - MONGO_DATA_DIR=/data/db
            - MONGO_LOG_DIR=/dev/null
        volumes:
            - testitoff-search-mongodb:/data/db
        networks:
            - testitoff-search-network
        expose:
            - "27017"
        ports:
            - "12017:27017" 

  testitoff-scene-webapi:
        image: registry.gitlab.com/kinalisoft/test-it-off/scene:0.2.0
        container_name: "testitoff-scene"
        restart: always
        ports:
            - "15000:15000"
        networks:
            - testitoff-robot-network
        environment:
            - ROBOTSYSTEM_SERVICE_URL=http://testitoff-robotsystem-webapi:14000  

  testitoff-statistic-webapi:
        image: registry.gitlab.com/kinalisoft/test-it-off/statistic:0.3.0
        container_name: "testitoff-statistic-webapi"
        privileged: true
        restart: always
        environment:
          - MONGODB_URL=testitoff-statistic-mongodb:27017
        ports:
          - "16000:16000"
        networks:
          - testitoff-statistic-network

  testitoff-statistic-mongodb:
        image: mongo:4.2.0-bionic
        container_name: "testitoff-statistic-mongodb"
        restart: always
        environment:
            - MONGO_DATA_DIR=/data/db
            - MONGO_LOG_DIR=/dev/null
        volumes:
            - testitoff-statistic-mongodb:/data/db
        networks:
            - testitoff-statistic-network
        expose:
            - "27017"
        ports:
            - "16017:27017"

  project:
    image: registry.gitlab.com/kinalisoft/test-it-off/project:0.4.0
    container_name: "project"
    ports:
      - "10000-10001:10000-10001"
    environment:
      MONGODB_URL: mongodb:27017
    links:
        - mongodb
    depends_on:
        - mongodb
    networks:
      - testitoff-robot-network

  mongodb:
    image: mongo:4.2.0-bionic
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - mongodb:/data/db
    expose:
      - "27017"
    networks:
      - testitoff-robot-network


  testitoff-interaction-webapi:
    image: registry.gitlab.com/kinalisoft/test-it-off/interaction:0.1.1
    container_name: "testitoff-interaction-webapi"
    privileged: true
    restart: always
    environment:
      - MONGODB_URL=testitoff-interaction-mongodb:27017
    ports:
      - "17000:17000"
    networks:
      - testitoff-interaction-network

  testitoff-interaction-mongodb:
        image: mongo:4.2.0-bionic
        container_name: "testitoff-interaction-mongodb"
        restart: always
        environment:
            - MONGO_DATA_DIR=/data/db
            - MONGO_LOG_DIR=/dev/null
        volumes:
            - testitoff-interaction-mongodb:/data/db
        networks:
            - testitoff-interaction-network
        expose:
            - "27017"
        ports:
            - "17017:27017"


volumes:
  mongodb:   
  testitoff-robot-mongodb:  
  testitoff-search-mongodb:
  testitoff-barcode-mongodb:
  testitoff-statistic-mongodb:
  testitoff-interaction-mongodb:
  testitoff-robotsystem-mongodb:
  execution-proxy:
  execution:

networks:
  testitoff-robot-network: 
  testitoff-search-network:
  testitoff-barcode-network:
  testitoff-statistic-network:
  testitoff-interaction-network:

