version: '3.8'

services:
  fit-demo-dobot-magician:
    environment:
      - ARCOR2_DOBOT_MOCK=false
      - ARCOR2_DOBOT_BIAS_X=0.06
      - ARCOR2_DOBOT_BIAS_Z=-0.06
    devices:
      - /dev/dobotMagician:/dev/dobot
  fit-demo-dobot-magician2:
    environment:
      - ARCOR2_DOBOT_MOCK=false
      - ARCOR2_DOBOT_BIAS_X=0.06
      - ARCOR2_DOBOT_BIAS_Z=-0.06
    devices:
      - /dev/dobotMagician2:/dev/dobot

  fit-demo-dobot-m1:
    environment:
      - ARCOR2_DOBOT_MOCK=false
    devices:
      - /dev/dobotM1:/dev/dobot

# Kinect in docker is available only in MOCK mode.
# Read README.md located in src/python/arcor2_kinect_azure for running locally
#  fit-demo-kinect:
#    environment:
#      - DISPLAY=$DISPLAY
#      - ARCOR2_KINECT_AZURE_MOCK=false
#    # Pass connected kinect to container
#    devices:
#      - /dev/bus/usb/:/dev/bus/usb/
#    # https://docs.docker.com/compose/gpu-support/
#    deploy:
#      resources:
#        reservations:
#          devices:
#            - capabilities: [gpu]
#    volumes:
#      - /tmp/.X11-unix:/tmp/.X11-unix:ro
